### ISSUE TITLE
Unknown initial character set index '255' received from server

### ISSUE THREAD

**Issue by IonicEcko** [Pugmatt/BedrockConnect#3]
I am getting the following error when attempting to run the latest version against Java 1.8.0.231.

ERROR: Could not connect to MySQL server! because: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.

Have tried changing the encoding and whatnot but don't seem to be making any progress.

**Comment by Runear** [comment]
Looks like this is related to MySQL v8 released recently. Running 5.7 works properly.

**Comment by maitriipatel** [comment]
is there any solution of version 8 for this type of error?

**Comment by Pugmatt** [comment]
Issue has now been fixed with updating MySQL Connector version to v8. Sorry for the wait!

**Comment by ManiAmit** [comment]
Unknown initial character set index '255' received from server


I am using latest version of jdk, jre, jdbc connector, mysql and tomcat server. 
Every possible solution applied, but this problem is not solved.
I am facing this problem only in myeclipse ide, other ide run the code

**Comment by Nitin69** [comment]
did you get any solution for this problem. I am facing the same problem while creating servlet in netbeans. My mysql version is 8.0.15 and i am getting this error 19-Oct-2020 17:28:32.054 SEVERE [main] MyListener.contextInitialized null
	java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
		I am not using Listener.

**Comment by nikkul** [comment]
You can download jar from the latest link. Latest JAR is required. Worked for me:

https://dev.mysql.com/downloads/file/?id=498587

**Comment by Rahul02-01** [comment]
thanks buddy @nikkul for the link...it solved the problem
