### ISSUE TITLE
Bedrock 1.19.20 update

### ISSUE THREAD

**Issue by dnsBlah** [Pugmatt/BedrockConnect#311]
### What happened?

Unable to join 1.19.20 servers

### Excepted Behaviour?

Expected to be able to join xD

### Steps to reproduce.

Join the BedrockConnect instance

### Minecraft Bedrock Version

1.19.20

### Console

Nintendo Switch

### Additional Context

Can you please update the instance <3

**Comment by kmpoppe** [comment]
It'll take some time for the implemented protocol project to update and then going into BC. Just a little patience, the server just released today :-)

**Comment by dnsBlah** [comment]
I fully understand, unfortunately my daughter wants to play 🤣
She doesn't understand it :(
iOS also upgraded 1hr ago x.x

**Comment by zellyn** [comment]
@kmpoppe would a PR be helpful, or are you all already fixing it? Looks like bumping the protocol library to 2.9.11-SNAPSHOT and changing the default version to 544 should do it, right?

**Comment by Pugmatt** [comment]
Working on it now. Thank you for your patience everyone.

**Comment by Pugmatt** [comment]
Was able to bump the Protocol version. Joins and displays form list without issue. Looks like an error occurs from the Protocol library when trying to call getFormData() from the ModalFormResponsePacket after a button is clicked, the data appears corrupted.

```
[Network Listener - #3] WARN io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$124/1559417428@1505c3a0
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at main.com.pyratron.pugmatt.bedrockconnect.listeners.PacketHandler.handle(PacketHandler.java:101)
        at com.pyratron.pugmatt.protocol.bedrock.packet.ModalFormResponsePacket.handle(ModalFormResponsePacket.java:22)
        at com.pyratron.pugmatt.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:29)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:284)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Unknown Source)
```

@Camotoy Not sure if you have any insight on this. I can post an issue in the Protocol repository as well so it's properly tracked, assuming this isn't a silly mistake on my end. Here's the current changes: https://github.com/Pugmatt/BedrockConnect/commit/93e91a83a8e2d64453898846d06f5615312e46bd

**Comment by Camotoy** [comment]
Geyser is running into the same issue.

**Comment by Camotoy** [comment]
Fixed; it should require no changes on your end. Just a silly mistake.

**Comment by jordan-da** [comment]
You folks are legends, thank you so much getting on top of this as fast as you have. I don't think any of us expected this to drop today.

**Comment by Pugmatt** [comment]
> Fixed; it should require no changes on your end. Just a silly mistake.

You're awesome, thank you 👍

The main BedrockConnect server has now been updated to 1.19.20. I'm seeing some other errors being thrown, but I don't _believe_ it should be affecting players from what I'm seeing. Will continue to look into it, but players should be able to join and use it.

**Comment by youforgottofollow** [comment]
its working again thanks for fixing so fast

**Comment by Pugmatt** [comment]
Released the JAR for the new version. Errors might still occur, but it should function for now to cover the new update, and players themselves shouldn't be experiencing issues from the errors. Will release a hot patch later for the possible errors.

**Comment by dnsBlah** [comment]
They've done it again!
Much love guys!

**Comment by Camotoy** [comment]
We’re experiencing form issues as well. I’ll update here once we figure out what’s up.
