### ISSUE TITLE
Crash on startup with 1.45

### ISSUE THREAD

**Issue by tomgray** [Pugmatt/BedrockConnect#501]
### What happened?

Crash on startup after upgrading from 1.43 to 1.45:

```
Failed to receive blocks palette
Exception in thread "main" java.lang.AssertionError: java.lang.IndexOutOfBoundsException: Tag type id must be greater than 0 and less than 12
         at main.com.pyratron.pugmatt.bedrockconnect.utils.PaletteManager.<init>(PaletteManager.java:124)
         at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:54)
 Caused by: java.lang.IndexOutOfBoundsException: Tag type id must be greater than 0 and less than 12
         at org.cloudburstmc.nbt.NbtType.byId(NbtType.java:46)
         at org.cloudburstmc.nbt.NBTInputStream.readTag(NBTInputStream.java:54)
         at org.cloudburstmc.nbt.NBTInputStream.readTag(NBTInputStream.java:46)
         at main.com.pyratron.pugmatt.bedrockconnect.utils.PaletteManager.<init>(PaletteManager.java:120)
         ... 1 more
```

### Expected Behaviour?

Server was starting without error prior to updating.

### Minecraft Bedrock Version

1.21.0.03

### Console

Windows

**Comment by sircurse** [comment]
Same problem on update

**Comment by tolookah** [comment]
you beat me by a minute, I have the same problem, running a docker image on debian.

**Comment by GERDominik165** [comment]
same by me

[Pterodactyl Daemon]: Finished pulling Docker container image
container@pelican~ java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharing)
container@pelican~ java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true port=2019 custom_servers=./1normal.json featured_servers=false kick_inactive=true user_servers=true
-= BedrockConnect (Release: 1.45) =-
Failed to receive blocks palette
Exception in thread "main" java.lang.AssertionError: java.lang.IndexOutOfBoundsException: Tag type id must be greater than 0 and less than 12
        at main.com.pyratron.pugmatt.bedrockconnect.utils.PaletteManager.<init>(PaletteManager.java:124)
        at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:54)
Caused by: java.lang.IndexOutOfBoundsException: Tag type id must be greater than 0 and less than 12
        at org.cloudburstmc.nbt.NbtType.byId(NbtType.java:46)
        at org.cloudburstmc.nbt.NBTInputStream.readTag(NBTInputStream.java:54)
        at org.cloudburstmc.nbt.NBTInputStream.readTag(NBTInputStream.java:46)
        at main.com.pyratron.pugmatt.bedrockconnect.utils.PaletteManager.<init>(PaletteManager.java:120)
        ... 1 more

**Comment by Pugmatt** [comment]
Not sure why the auto-released version broke, but I've gone in and re-uploaded the working JAR + zip manually. Try re-downloading from the same release and it should work now https://github.com/Pugmatt/BedrockConnect/releases/tag/1.45

**Comment by tolookah** [comment]
That resolved it, thanks!  (I ran docker compose pull && docker compose down && docker compose up -d to update everything
)

**Comment by CoveWolf** [comment]
Thanks for all your hard work Pugmatt! It works now. Thank you for your quick responses.

**Comment by tomgray** [comment]
I'm building from source and unfortunately I still have the issue.

**Comment by tomgray** [comment]
Here are my build logs:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.pyratron.pugmatt:BedrockConnect >-----------------
[INFO] Building BedrockConnect 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ BedrockConnect ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 10 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.6.1:compile (default-compile) @ BedrockConnect ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/classes
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java: /private/tmp/nix-build-bedrock-connect-1.4>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java: Recompile with -Xlint:deprecation for deta>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/utils/PaletteManager.java: Some input files use unchecked or unsafe oper>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/utils/PaletteManager.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ BedrockConnect ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/test/resources
[INFO] 
[INFO] --- compiler:3.6.1:testCompile (default-testCompile) @ BedrockConnect ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ BedrockConnect ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.1.0:jar (default-jar) @ BedrockConnect ---
[INFO] Building jar: /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/BedrockConnect-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- shade:3.2.1:shade (default) @ BedrockConnect ---
[INFO] Including org.cloudburstmc.protocol:bedrock-connection:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.protocol:bedrock-codec:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.protocol:common:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:int-object-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:int-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:int-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:object-int-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.math:immutable:jar:2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.nukkitx:natives:jar:1.0.3 in the shaded jar.
[INFO] Including io.netty:netty-buffer:jar:4.1.101.Final in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:long-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil:core:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:long-object-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:object-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:object-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:long-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.bitbucket.b_c:jose4j:jar:0.9.3 in the shaded jar.
[INFO] Including org.cloudburstmc:nbt:jar:3.0.3.Final in the shaded jar.
[INFO] Including org.cloudburstmc.netty:netty-transport-raknet:jar:1.0.0.CR3-SNAPSHOT in the shaded jar.
[INFO] Including io.netty:netty-common:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-codec:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-transport:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver:jar:4.1.101.Final in the shaded jar.
[INFO] Including net.jodah:expiringmap:jar:0.5.10 in the shaded jar.
[INFO] Including io.airlift:aircompressor:jar:0.25 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.8.9 in the shaded jar.
[INFO] Including com.googlecode.json-simple:json-simple:jar:1.1.1 in the shaded jar.
[INFO] Including junit:junit:jar:4.10 in the shaded jar.
[INFO] Including org.hamcrest:hamcrest-core:jar:1.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.12.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.23 in the shaded jar.
[INFO] Including mysql:mysql-connector-java:jar:8.0.28 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.11.4 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.21 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.21 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.pyratron.pugmatt:BedrockConnect >-----------------
[INFO] Building BedrockConnect 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ BedrockConnect ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 10 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.6.1:compile (default-compile) @ BedrockConnect ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/classes
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java: /private/tmp/nix-build-bedrock-connect-1.4>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java: Recompile with -Xlint:deprecation for deta>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/utils/PaletteManager.java: Some input files use unchecked or unsafe oper>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/utils/PaletteManager.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ BedrockConnect ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/test/resources
[INFO] 
[INFO] --- compiler:3.6.1:testCompile (default-testCompile) @ BedrockConnect ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ BedrockConnect ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.1.0:jar (default-jar) @ BedrockConnect ---
[INFO] Building jar: /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/BedrockConnect-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- shade:3.2.1:shade (default) @ BedrockConnect ---
[INFO] Including org.cloudburstmc.protocol:bedrock-connection:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.protocol:bedrock-codec:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.protocol:common:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:int-object-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:int-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:int-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:object-int-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.math:immutable:jar:2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.nukkitx:natives:jar:1.0.3 in the shaded jar.
[INFO] Including io.netty:netty-buffer:jar:4.1.101.Final in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:long-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil:core:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:long-object-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:object-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:object-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:long-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.bitbucket.b_c:jose4j:jar:0.9.3 in the shaded jar.
[INFO] Including org.cloudburstmc:nbt:jar:3.0.3.Final in the shaded jar.
[INFO] Including org.cloudburstmc.netty:netty-transport-raknet:jar:1.0.0.CR3-SNAPSHOT in the shaded jar.
[INFO] Including io.netty:netty-common:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-codec:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-transport:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver:jar:4.1.101.Final in the shaded jar.
[INFO] Including net.jodah:expiringmap:jar:0.5.10 in the shaded jar.
[INFO] Including io.airlift:aircompressor:jar:0.25 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.8.9 in the shaded jar.
[INFO] Including com.googlecode.json-simple:json-simple:jar:1.1.1 in the shaded jar.
[INFO] Including junit:junit:jar:4.10 in the shaded jar.
[INFO] Including org.hamcrest:hamcrest-core:jar:1.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.12.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.23 in the shaded jar.
[INFO] Including mysql:mysql-connector-java:jar:8.0.28 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.11.4 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.21 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.21 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.pyratron.pugmatt:BedrockConnect >-----------------
[INFO] Building BedrockConnect 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ BedrockConnect ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 10 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.6.1:compile (default-compile) @ BedrockConnect ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/classes
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java: /private/tmp/nix-build-bedrock-connect-1.4>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java: Recompile with -Xlint:deprecation for deta>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/utils/PaletteManager.java: Some input files use unchecked or unsafe oper>
[INFO] /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/utils/PaletteManager.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ BedrockConnect ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/src/test/resources
[INFO] 
[INFO] --- compiler:3.6.1:testCompile (default-testCompile) @ BedrockConnect ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ BedrockConnect ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.1.0:jar (default-jar) @ BedrockConnect ---
[INFO] Building jar: /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/BedrockConnect-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- shade:3.2.1:shade (default) @ BedrockConnect ---
[INFO] Including org.cloudburstmc.protocol:bedrock-connection:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.protocol:bedrock-codec:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.protocol:common:jar:3.0.0.Beta2-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:int-object-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:int-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:int-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:object-int-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.math:immutable:jar:2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.nukkitx:natives:jar:1.0.3 in the shaded jar.
[INFO] Including io.netty:netty-buffer:jar:4.1.101.Final in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:long-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil:core:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.maps:long-object-maps:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:object-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.commons:object-common:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.cloudburstmc.fastutil.sets:long-sets:jar:8.5.13-SNAPSHOT in the shaded jar.
[INFO] Including org.bitbucket.b_c:jose4j:jar:0.9.3 in the shaded jar.
[INFO] Including org.cloudburstmc:nbt:jar:3.0.3.Final in the shaded jar.
[INFO] Including org.cloudburstmc.netty:netty-transport-raknet:jar:1.0.0.CR3-SNAPSHOT in the shaded jar.
[INFO] Including io.netty:netty-common:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-codec:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-transport:jar:4.1.101.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver:jar:4.1.101.Final in the shaded jar.
[INFO] Including net.jodah:expiringmap:jar:0.5.10 in the shaded jar.
[INFO] Including io.airlift:aircompressor:jar:0.25 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.8.9 in the shaded jar.
[INFO] Including com.googlecode.json-simple:json-simple:jar:1.1.1 in the shaded jar.
[INFO] Including junit:junit:jar:4.10 in the shaded jar.
[INFO] Including org.hamcrest:hamcrest-core:jar:1.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.12.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.23 in the shaded jar.
[INFO] Including mysql:mysql-connector-java:jar:8.0.28 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.11.4 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.21 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.21 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] hamcrest-core-1.1.jar, junit-4.10.jar define 21 overlapping classes: 
[WARNING]   - org.hamcrest.internal.SelfDescribingValue
[WARNING]   - org.hamcrest.Description
[WARNING]   - org.hamcrest.CoreMatchers
[WARNING]   - org.hamcrest.core.AllOf
[WARNING]   - org.hamcrest.SelfDescribing
[WARNING]   - org.hamcrest.core.IsSame
[WARNING]   - org.hamcrest.BaseDescription
[WARNING]   - org.hamcrest.core.DescribedAs
[WARNING]   - org.hamcrest.Factory
[WARNING]   - org.hamcrest.internal.ArrayIterator
[WARNING]   - 11 more...
[WARNING] core-8.5.13-SNAPSHOT.jar, object-common-8.5.13-SNAPSHOT.jar define 2 overlapping classes: 
[WARNING]   - it.unimi.dsi.fastutil.objects.ObjectObjectImmutablePair
[WARNING]   - it.unimi.dsi.fastutil.objects.ObjectObjectImmutableSortedPair
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/target/BedrockConnect-1.0-SNAPSHOT.jar with /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/server>
[INFO] Dependency-reduced POM written at: /private/tmp/nix-build-bedrock-connect-1.45.drv-0/source/serverlist-server/dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.345 s
[INFO] Finished at: 2024-06-13T18:34:36Z
[INFO] ------------------------------------------------------------------------
```

It appears that the updated version of org.cloudburstmc.protocol:bedrock-connection:jar:3.0.0.Beta2-SNAPSHOT is getting included correctly.

**Comment by GERDominik165** [comment]
> Not sure why the auto-released version broke, but I've gone in and re-uploaded the working JAR + zip manually. Try re-downloading from the same release and it should work now https://github.com/Pugmatt/BedrockConnect/releases/tag/1.45

with them i have in minecraft "the host is using an older version"

**Comment by Pugmatt** [comment]
> I'm building from source and unfortunately I still have the issue.

Please pull the newest commit, "Revert updated runtime_block_states.dat", and run a fresh build. Should fix it.

**Comment by GERDominik165** [comment]
https://github.com/Pugmatt/BedrockConnect/releases/tag/1.45

is not with 1.21 joinable

**Comment by Pugmatt** [comment]
> https://github.com/Pugmatt/BedrockConnect/releases/tag/1.45
> 
> is not with 1.21 joinable

It is working for others, so you may be running the wrong jar. Please ensure you see "(Release: 1.45)" in the log when launching. If not try re-downloading the JAR from the page again. Also make sure you are not playing on a Beta/Preview version of Minecraft.

**Comment by GERDominik165** [comment]
yes they is running

container@pelican~ java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true port=2001 custom_servers=./1normal.json featured_servers=false kick_inactive=true user_servers=true
-= BedrockConnect (Release: 1.45) =-

Server Limit: 100
Port: 2001

but if i try to connect with ps4 on 1.21.0 they say to me the server list btw is outdated

**Comment by Pugmatt** [comment]
> yes they is running
> 
> container@pelican~ java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true port=2001 custom_servers=./1normal.json featured_servers=false kick_inactive=true user_servers=true -= BedrockConnect (Release: 1.45) =-
> 
> Server Limit: 100 Port: 2001
> 
> but if i try to connect with ps4 on 1.21.0 they say to me the server list btw is outdated

I'm not sure then unfortunately. Your PS4 may have it's DNS pointing to a different BedrockConnect instance?

**Comment by tomgray** [comment]
> > I'm building from source and unfortunately I still have the issue.
> 
> Please pull the newest commit, "Revert updated runtime_block_states.dat", and run a fresh build. Should fix it.

Confirmed this fixes the issue for me (using latest commit `baa3454c6bd33020126d11be697509ab48807e8a`).

I can join servers running latest bedrock server release from latest client.

**Comment by tomgray** [comment]
My issue is fixed so closing this.

**Comment by GERDominik165** [comment]
> > yes they is running
> > container@pelican~ java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true port=2001 custom_servers=./1normal.json featured_servers=false kick_inactive=true user_servers=true -= BedrockConnect (Release: 1.45) =-
> > Server Limit: 100 Port: 2001
> > but if i try to connect with ps4 on 1.21.0 they say to me the server list btw is outdated
> 
> I'm not sure then unfortunately. Your PS4 may have it's DNS pointing to a different BedrockConnect instance?

i use this bedrock portal :https://github.com/LucienHH/bedrock-portal
to transfer players to server list 
if i change port to 1.21.0 BDS they can join , so i think your jar has something not updated to 1.21.0

**Comment by GERDominik165** [comment]
with 1.20.81 on ios (not did updated to last) i can join , but not with latest 1.21.0
